# Scans repo root for AGS web export folders and regenerates index.html + games.json.
$Root = Split-Path -Parent $PSScriptRoot

Add-Type -AssemblyName System.Web

$games = Get-ChildItem -Path $Root -Directory |
    Where-Object { $_.Name -notmatch '^\.' } |
    Where-Object {
        (Test-Path (Join-Path $_.FullName 'index.html')) -and
        (Test-Path (Join-Path $_.FullName 'ags.js'))
    } |
    ForEach-Object { $_.Name } |
    Sort-Object

$jsonPath = Join-Path $Root 'games.json'
$games | ConvertTo-Json | Set-Content -Path $jsonPath -Encoding UTF8

$links = foreach ($name in $games) {
    $encoded = [uri]::EscapeDataString($name)
    $safe = [System.Web.HttpUtility]::HtmlEncode($name)
    "    <li><a href=`"play.html?game=$encoded`">$safe</a></li>"
}

$listHtml = if ($games.Count -gt 0) {
    ($links -join "`n")
} else {
    '    <li><em>No games found. Copy an AGS web export folder here (needs index.html and ags.js).</em></li>'
}

$indexHtml = @"
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AGS Web Games</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 40rem; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }
    h1 { font-size: 1.5rem; }
    ul { padding-left: 1.25rem; }
    a { color: #0066cc; }
    footer { margin-top: 2rem; font-size: 0.85rem; color: #666; }
  </style>
</head>
<body>
  <h1>AGS Web Games</h1>
  <p>Dev test catalog - click a title to play.</p>
  <ul>
$listHtml
  </ul>
  <footer>Generated by scripts/generate-catalog.ps1 - run again after adding game folders.</footer>
</body>
</html>
"@

$indexPath = Join-Path $Root 'index.html'
[System.IO.File]::WriteAllText($indexPath, $indexHtml)

Write-Host "Found $($games.Count) game(s): $($games -join ', ')"
Write-Host "Wrote $indexPath and $jsonPath"
